
export default {
    GET_CAR_FORM_GETTER: 'GET_CAR_FORM_GETTER',
    GET_HEADERS_TABLE_GETTER: 'GET_HEADERS_TABLE_GETTER',
    GET_CARS_GETTERS: 'GET_CARS_GETTERS',
    GET_HEADERS_ITEMS_GETTER: 'GET_HEADERS_ITEMS_GETTER',
    GET_ITEMS_FORM_GETTER: 'GET_ITEMS_FORM_GETTER',
    GET_UN_SOLD_CARS_GETTER: 'GET_UN_SOLD_CARS_GETTER'
}